import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const deckSchema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'boards',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'color', type: 'string', isOptional: true },
        { name: 'archived', type: 'boolean' },
        { name: 'owner', type: 'string' },
        { name: 'shared', type: 'boolean' },
        { name: 'can_edit', type: 'boolean' },
        { name: 'can_manage', type: 'boolean' },
        { name: 'can_share', type: 'boolean' },
        { name: 'last_modified', type: 'number' },
        { name: 'etag', type: 'string', isOptional: true },
        { name: 'acl_json', type: 'string' },
        { name: 'users_json', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'stacks',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'board_id', type: 'string', isIndexed: true },
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'order', type: 'number' },
        { name: 'last_modified', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'cards',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'board_id', type: 'string', isIndexed: true },
        { name: 'stack_id', type: 'string', isIndexed: true },
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'order', type: 'number' },
        { name: 'owner', type: 'string' },
        { name: 'color', type: 'string', isOptional: true },
        { name: 'archived', type: 'boolean' },
        { name: 'done_at', type: 'number', isOptional: true },
        { name: 'duedate', type: 'number', isOptional: true, isIndexed: true },
        { name: 'startdate', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'last_modified', type: 'number' },
        { name: 'attachment_count', type: 'number' },
        { name: 'comments_count', type: 'number' },
        { name: 'dependent_cards_json', type: 'string' },
        { name: 'pending', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'labels',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'board_id', type: 'string', isIndexed: true },
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'color', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'card_labels',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'card_id', type: 'string', isIndexed: true },
        { name: 'label_id', type: 'string', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'card_assignees',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'card_id', type: 'string', isIndexed: true },
        { name: 'participant', type: 'string' },
        { name: 'assignee_type', type: 'number' },
        { name: 'display_name', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'comments',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'card_id', type: 'string', isIndexed: true },
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'message', type: 'string' },
        { name: 'actor_id', type: 'string' },
        { name: 'actor_display_name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'parent_id', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'attachments',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'card_id', type: 'string', isIndexed: true },
        { name: 'remote_id', type: 'string', isIndexed: true },
        { name: 'attachment_type', type: 'string' },
        { name: 'file_name', type: 'string' },
        { name: 'mime', type: 'string' },
        { name: 'size', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'created_by', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'outbox',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'kind', type: 'string' },
        { name: 'entity_type', type: 'string' },
        { name: 'entity_id', type: 'string', isIndexed: true },
        { name: 'payload_json', type: 'string' },
        { name: 'server_values_json', type: 'string' },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'attempts', type: 'number' },
        { name: 'next_attempt_at', type: 'number' },
        { name: 'last_error', type: 'string', isOptional: true },
        { name: 'state', type: 'string', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'recent_boards',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'board_id', type: 'string', isIndexed: true },
        { name: 'opened_at', type: 'number' },
      ],
    }),
  ],
});
